apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: library/rabbitmq:3.7.8-management
        command:
        ports:
          - containerPort: 5671
          - containerPort: 5672
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
  - protocol: TCP
    nodePort: 31671
    port: 5671
    targetPort: 5671
    name: amqp0
  - protocol: TCP
    nodePort: 31672
    port: 5672
    targetPort: 5672
    name: amqp1

