apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: waterservice
  labels:
    app: waterservice
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: waterservice
    spec:
      containers:
      - name: waterservice
        image: noctarius2k/waterservice:${TAG}
        command:
        ports:
          - containerPort: 8080
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
---
kind: Service
apiVersion: v1
metadata:
  name: waterservice
spec:
  type: LoadBalancer
  selector:
    app: waterservice
  ports:
  - protocol: TCP
    port: 3000
    targetPort 3000
    name: http
