apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: waterservice
  labels:
    app: waterservice
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: waterservice
    spec:
      containers:
      - name: waterservice
        image: gcr.io/acquired-rarity-236416/waterservice:${TAG}
        command:
        ports:
          - containerPort: 8080
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: JAEGER_ENDPOINT
            value: http://{INSTANA_AGENT_HOST}:14268/api/traces
          - name: JAEGER_SERVICE_NAME
            value: "waterservice"
---
kind: Service
apiVersion: v1
metadata:
  name: waterservice
spec:
  type: NodePort
  selector:
    app: waterservice
  ports:
  - protocol: TCP
    nodePort: 30012
    port: 80
    targetPort: 8080
    name: http

