apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: brewservice
  labels:
    app: brewservice
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: brewservice
    spec:
      containers:
      - name: brewservice
        image: gcr.io/acquired-rarity-236416/brewservice:${TAG}
        command:
        ports:
          - containerPort: 8080
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
---
kind: Service
apiVersion: v1
metadata:
  name: brewservice
spec:
  type: NodePort
  selector:
    app: brewservice
  ports:
  - protocol: TCP
    nodePort: 30011
    port: 80
    targetPort: 3000
    name: http

